<?php /* Template Name: Over mij */ get_header(); ?>
<main id="main-content" class="site-main about-playground">
    <div id="aboutGlow" class="about-glow" aria-hidden="true"></div>
    <section class="page-hero about-hero"><div class="container about-hero-grid"><div class="about-hero-copy"><p class="eyebrow">Over mij</p><h1 data-about-typewriter>Nieuwsgierig, praktisch en altijd in beweging.</h1><p class="intro">Ik ben Othman, een software developer in opleiding met interesse in zowel digitale producten als de techniek erachter.</p><p class="about-hint" aria-hidden="true">Psst &mdash; tik een skill-orb aan, ze stuiteren graag.</p></div><aside class="tomato-game tomato-game--hero" data-tomato-game aria-label="Tomaat-minigame (hero)"><div class="tomato-game__head"><p class="eyebrow">Minigame</p><p class="tomato-game__title">Vang de tomaat 🍅</p><p class="tomato-game__sub">30 seconden — beweeg het mandje.</p></div><div class="tomato-game__hud"><span>Score <strong data-tomato-score>0</strong></span><span>Tijd <strong data-tomato-time>30</strong>s</span><span>Best <strong data-tomato-best>0</strong></span></div><div class="tomato-game__field" data-tomato-field tabindex="0" role="application" aria-label="Vang de vallende tomaten met het mandje"><div class="tomato-game__basket" data-tomato-basket aria-hidden="true">🧺</div><p class="tomato-game__note" data-tomato-note>Druk op start — pijltjes / muis / vinger.</p></div><div class="tomato-game__actions"><button type="button" class="button button--primary" data-tomato-start>Start</button></div></aside></div></section>
    <section class="section container two-column"><div><p class="eyebrow">Mijn verhaal</p><h2>Leren door te doen.</h2></div><div class="prose"><p>Ik krijg energie van een idee omzetten in iets dat je kunt gebruiken. Ik werk graag stap voor stap: eerst begrijpen wat nodig is, daarna bouwen, testen en verbeteren.</p><p>Mijn projecten lopen uiteen van webdevelopment tot hardware en games. Die combinatie heeft mij geleerd om verder te kijken dan alleen de code.</p></div></section>
    <section class="section section--tint"><div class="container two-column"><div><p class="eyebrow">Focus</p><h2>Waar ik naartoe wil.</h2></div><div class="fact-list"><div><strong>01</strong><span>Een stageplek vinden waar ik aan echte producten werk.</span></div><div><strong>02</strong><span>Mijn vaardigheden in back-end en front-end verder verdiepen.</span></div><div><strong>03</strong><span>Leren samenwerken in een professioneel developmentteam.</span></div></div></div></section>
    <section class="section container"><p class="eyebrow">In cijfers</p><div class="stats"><div class="stat"><span class="stat-num" data-count="3">03</span><span class="stat-label">Jaren aan het leren</span></div><div class="stat"><span class="stat-num" data-count="6">06</span><span class="stat-label">Uitgelichte projecten</span></div><div class="stat"><span class="stat-num" data-count="8">08</span><span class="stat-label">Vaardigheden &amp; tools</span></div></div></section>
    <section class="section container"><p class="eyebrow">Skills</p><div class="skills-list about-orbs"><button type="button" data-orb>PHP</button><button type="button" data-orb>WordPress</button><button type="button" data-orb>JavaScript</button><button type="button" data-orb>HTML &amp; CSS</button><button type="button" data-orb>C#</button><button type="button" data-orb>Raspberry Pi</button><button type="button" data-orb>Git</button><button type="button" data-orb>Responsive design</button></div></section>
    <section class="section section--tint"><div class="container"><div class="tomato-game tomato-game--full" data-tomato-game aria-label="Tomaat-minigame (onderaan)"><div class="tomato-game__head"><p class="eyebrow">Minigame</p><p class="tomato-game__title">Vang de tomaat 🍅</p><p class="tomato-game__sub">30 seconden — beweeg het mandje met muis, vinger of pijltjes. Kies daarna je favoriete plek: hero of hier.</p></div><div class="tomato-game__hud"><span>Score <strong data-tomato-score>0</strong></span><span>Tijd <strong data-tomato-time>30</strong>s</span><span>Best <strong data-tomato-best>0</strong></span></div><div class="tomato-game__field" data-tomato-field tabindex="0" role="application" aria-label="Vang de vallende tomaten met het mandje"><div class="tomato-game__basket" data-tomato-basket aria-hidden="true">🧺</div><p class="tomato-game__note" data-tomato-note>Druk op start — pijltjes / muis / vinger.</p></div><div class="tomato-game__actions"><button type="button" class="button button--primary" data-tomato-start>Start</button><noscript><p class="tomato-game__fallback">Zonder JavaScript geen vallende tomaten — het verhaal hierboven blijft volledig leesbaar.</p></noscript></div></div></div></section>
</main>
<?php get_footer(); ?>